version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.5.3-stretch-node
    steps:
    - checkout
    - run:
        name: Which bundler?
        command: bundle -v
    - run:
        command: bundle install --path vendor/bundle
    - run: echo "hello world" 
workflows:
  version: 2
  workflow:
    jobs:
    - build