version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.5.3-node-browsers
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          gem update --system
          gem install bundler
          gem sources --remove https://gems.ruby-china.com/ --add https://rubygems.org/
          bundler update --bundler
          bundle install --jobs=4 --retry=3 --path vendor/bundle
workflows:
  version: 2
  workflow:
    jobs:
    - build