# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Ruby
        uses: actions/setup-ruby@v1.0.0
        with:
          # Version range or exact version of a Ruby version to use.
          version: 2.5 # optional, default is >= 2.4

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Cache gems
        uses: actions/cache@v1
        env:
          cache-name: cache-gems
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Build and test with rspec
        env:
          RAILS_ENV: test
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec rails db:create
          bundle exec rails db:migrate
          mkdir /tmp/test-results
          bundle exec rspec --format RspecJunitFormatter \
                          --out /tmp/test-results/rspec.xml \
                          --format documentation

      - name: Archive test results
        uses: actions/upload-artifact@v1
        with:
          name: rspec-report
          path: /tmp/test-results/rspec.xml
